# Generated by Django 4.0.3 on 2022-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_type_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='pseudo',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
