# Generated by Django 4.0.3 on 2022-06-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_personne_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('realisateur', models.CharField(max_length=50)),
                ('acteur_principal', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=100000)),
                ('note', models.IntegerField()),
            ],
        ),
    ]
