# Generated by Django 4.0.3 on 2022-06-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_realisateur_alter_film_annee_alter_film_realisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='acteur_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.act'),
        ),
        migrations.AlterField(
            model_name='film',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cat'),
        ),
    ]
